site_name: My Docs
nav:
  - Home: index.md
  - Web-Based IK Rig & Keyframe Editor: project0.md
  - Node Graph Visualizer: project3.md
  - WebGL Stereoscopic Display: project2.md
  - Interactive Mickey Lite-Brite Display: project1.md
  - OpenGL Mesh Viewer: project4.md
  - VR Music Video: project6.md
  

theme: readthedocs
icon: src/portfolio_icon.png
