site_name: Creative Technology Portfolio
nav:
  - Home: index.md
  - Web-Based IK Rig & Keyframe Editor: project0.md
  - Node Graph Visualizer: project3.md
  - OpenGL Mesh Viewer: project4.md
  - C++ Ray Tracer: project5.md
  - Python Ray Tracer (Blender Plugin): project7.md
  - Blender Projects: project8.md
  - Interactive Lite-Brite Toy: project1.md
  - VR Music Video: project6.md
  - Animation Reel: https://youtu.be/pZt7602uW6c?si=uqKWJ8O0utF4P-99
 

theme: readthedocs
icon: src/portfolio_icon.png
